DROP TABLE IF EXISTS tb_herois;
CREATE TABLE tb_herois(
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    NOME TEXT NOT NULL,
    PODER TEXT NOT NULL
)

INSERT INTO tb_herois (NOME, PODER) VALUES ('FLASH','VELOCIDADE'),('AQUAMAN','FALAR ANIMAIS'),('BATMAN','DINHEIRO')

SELECT * FROM tb_herois where nome = 'FLASH'

UPDATE tb_herois SET NOME='GOKU', PODER='DEUS' WHERE ID = 1

DELETE FROM tb_herois WHERE ID = 2